import Config from 'react-native-config';

export interface MethodObject {
  description: string;
  isAuthenticated: boolean;
  verb: 'GET' | 'POST' | 'PUT' | 'DELETE';
  sendDeviceKey: boolean;
  jsonMethod: boolean;
  suffixUrl: string;
  mustStringify: boolean;
  isFlatResponse: boolean;
  openAi: boolean;
  contentType: string;
  isBeta: boolean;
  isPicsUrl: boolean;
}

export interface ConfigType {
  baseUrl: string;
  openAiUrl: string;
  picsUrl: string;
  openAiKey: string;
  geminiAPIKey: string;
  picGeneration: string;
  assemblyAIURL: string;
  transcriptionByOpenAI: boolean;
  masterAdminCode: string;
  methods: Record<string, MethodObject>;
}

const AppConfig: ConfigType = {
  baseUrl: 'https://matalkapi-copy-nologin.up.railway.app',
  //baseUrl: 'http://192.168.1.175:3000',
  //baseUrl: 'http://localhost:3000',
  openAiUrl: 'https://api.openai.com/v1',
  picsUrl: 'https://image.pollinations.ai/prompt',
  geminiAPIKey: Config.GEMINI_API_KEY || '',
  picGeneration: 'polli',
  transcriptionByOpenAI: true,
  assemblyAIURL: 'https://api.assemblyai.com/v2',
  openAiKey: Config.OPENAI_API_KEY || '',
  masterAdminCode: '7856',

  methods: {
    registerUser: {
      description: 'registerUser',
      isAuthenticated: false,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/auth/local/register',
      mustStringify: true,
      isFlatResponse: false,
      openAi: false,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    saveFCM: {
      description: 'saveFCM',
      isAuthenticated: false,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/auth/local/fcm',
      mustStringify: true,
      isFlatResponse: false,
      openAi: false,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    transcribeAudio: {
      description: 'transcribeAudio',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/audio/transcriptions',
      mustStringify: true,
      isFlatResponse: false,
      openAi: true,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'multipart/form-data',
    },
    transcribeAudioAssembly: {
      description: 'transcribeAudioAssembly',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/audio/transcriptions',
      mustStringify: true,
      isFlatResponse: false,
      openAi: true,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'multipart/form-data',
    },
    uploadAudioAssemblyAI: {
      description: 'uploadAudioAssemblyAI',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/audio/transcriptions',
      mustStringify: true,
      isFlatResponse: false,
      openAi: true,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'multipart/form-data',
    },
    assistantAPI: {
      description: 'chat',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/chat/completions',
      mustStringify: true,
      isFlatResponse: false,
      openAi: true,
      isBeta: true,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    chatCompletion: {
      description: 'chatCompletion',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/chat/completions',
      mustStringify: true,
      isFlatResponse: false,
      openAi: true,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    createThread: {
      description: 'createThread',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/threads',
      mustStringify: true,
      isFlatResponse: false,
      openAi: true,
      isBeta: true,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    sendMessage: {
      description: 'sendMessage',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/threads/{thread_id}/messages',
      mustStringify: true,
      isFlatResponse: false,
      openAi: true,
      isBeta: true,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    runAssistant: {
      description: 'runAssistant',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/threads/{thread_id}/runs',
      mustStringify: true,
      isFlatResponse: false,
      openAi: true,
      isBeta: true,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    checkRunStatus: {
      description: 'checkRunStatus',
      isAuthenticated: true,
      verb: 'GET',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/threads/{thread_id}/runs/{run_id}',
      mustStringify: false,
      isFlatResponse: false,
      openAi: true,
      isBeta: true,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    getMessages: {
      description: 'getMessages',
      isAuthenticated: true,
      verb: 'GET',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/threads/{thread_id}/messages?limit=10&order=desc',
      mustStringify: false,
      isFlatResponse: false,
      openAi: true,
      isBeta: true,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    generateImage: {
      description: 'generateImage',
      isAuthenticated: false,
      verb: 'GET',
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: '/{prompt}?width=200&height=200&seed={seed}',
      mustStringify: false,
      isFlatResponse: true,
      openAi: false,
      isBeta: false,
      isPicsUrl: true,
      contentType: 'application/json',
    },
    generateAnswers: {
      description: 'generateAnswers',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/answers/generate',
      mustStringify: true,
      isFlatResponse: false,
      openAi: false,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    logconversation: {
      description: 'logconversation',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/logconversation',
      mustStringify: true,
      isFlatResponse: false,
      openAi: false,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    loginitconversation: {
      description: 'loginitconversation',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/loginitconversation',
      mustStringify: true,
      isFlatResponse: false,
      openAi: false,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    processImages: {
      description: 'processImages',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/process-images',
      mustStringify: true,
      isFlatResponse: false,
      openAi: false,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    processImagesConvo: {
      description: 'processImagesConvo',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/process-images-convo',
      mustStringify: true,
      isFlatResponse: false,
      openAi: false,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    wakeup: {
      description: 'wakeup',
      isAuthenticated: false,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: '/wakeup',
      mustStringify: false,
      isFlatResponse: false,
      openAi: false,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    getAssistantId: {
      description: 'getAssistantId',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/get-assistant',
      mustStringify: true,
      isFlatResponse: false,
      openAi: false,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    deleteAccount: {
      description: 'deleteAccount',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/delete-assistant',
      mustStringify: true,
      isFlatResponse: false,
      openAi: false,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    makeAssistantId: {
      description: 'makeAssistantId',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/make-assistant',
      mustStringify: true,
      isFlatResponse: false,
      openAi: false,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    validateReceipt: {
      description: 'validateReceipt',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/validate-receipt',
      mustStringify: true,
      isFlatResponse: false,
      openAi: false,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    validateGoogleReceipt: {
      description: 'validateGoogleReceipt',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/validate-google-play-receipt',
      mustStringify: true,
      isFlatResponse: false,
      openAi: false,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    searchWordImages: {
      description: 'searchWordImages',
      isAuthenticated: true,
      verb: 'GET',
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: '/api/words/search?q={q}&limit={limit}',
      mustStringify: false,
      isFlatResponse: false,
      openAi: false,
      isBeta: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
  },
};

export default AppConfig;
