import Config from 'react-native-config';

export interface MethodObject {
  description: string;
  isAuthenticated: boolean;
  verb: 'GET' | 'POST' | 'PUT' | 'DELETE';
  sendDeviceKey: boolean;
  jsonMethod: boolean;
  suffixUrl: string;
  mustStringify: boolean;
  isFlatResponse: boolean;
  contentType: string;
  isPicsUrl: boolean;
}

export interface ConfigType {
  baseUrl: string;
  picsUrl: string;
  geminiAPIKey: string;
  picGeneration: string;
  assemblyAIURL: string;
  masterAdminCode: string;
  methods: Record<string, MethodObject>;
}

const AppConfig: ConfigType = {
  baseUrl: 'https://matalkapi-production.up.railway.app',
  //baseUrl: 'http://192.168.1.175:3000',
  //baseUrl: 'http://localhost:3000',
  picsUrl: 'https://image.pollinations.ai/prompt',
  geminiAPIKey: Config.GEMINI_API_KEY || '',
  picGeneration: 'polli',
  assemblyAIURL: 'https://api.assemblyai.com/v2',
  masterAdminCode: '78567',

  methods: {
    registerUser: {
      description: 'registerUser',
      isAuthenticated: false,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/auth/local/register',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    saveFCM: {
      description: 'saveFCM',
      isAuthenticated: false,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/auth/local/fcm',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    generateImage: {
      description: 'generateImage',
      isAuthenticated: false,
      verb: 'GET',
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: '/{prompt}?width=200&height=200&seed={seed}',
      mustStringify: false,
      isFlatResponse: true,
      isPicsUrl: true,
      contentType: 'application/json',
    },
    generateAnswers: {
      description: 'generateAnswers',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/answers/generate-adult',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    logconversation: {
      description: 'logconversation',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/logconversation',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    loginitconversation: {
      description: 'loginitconversation',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/loginitconversation',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    processImages: {
      description: 'processImages',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/process-images',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    processImagesConvo: {
      description: 'processImagesConvo',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/process-images-convo',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    wakeup: {
      description: 'wakeup',
      isAuthenticated: false,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: '/wakeup',
      mustStringify: false,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    getAssistantId: {
      description: 'getAssistantId',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/get-assistant',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    deleteAccount: {
      description: 'deleteAccount',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/delete-assistant',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    makeAssistantId: {
      description: 'makeAssistantId',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/make-assistant',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    validateReceipt: {
      description: 'validateReceipt',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/validate-receipt',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    validateGoogleReceipt: {
      description: 'validateGoogleReceipt',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/validate-google-play-receipt',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    searchWordImages: {
      description: 'searchWordImages',
      isAuthenticated: true,
      verb: 'GET',
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: '/api/words/search?q={q}&limit={limit}',
      mustStringify: false,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    searchGoogleImages: {
      description: 'searchGoogleImages',
      isAuthenticated: true,
      verb: 'GET',
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: '/api/google-images/search?q={q}&limit={limit}',
      mustStringify: false,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    polishApi: {
      description: 'polishApi',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/polish-text',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    validateCode: {
      description: 'validateCode',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/org/validate-code',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    magicBuild: {
      description: 'magicBuild',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/api/context/magic-build',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    enrollDevice: {
      description: 'enrollDevice',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/org/enroll',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    magicUpdate: {
      description: 'magicUpdate',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/api/context/magic-update',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    bootstrap: {
      description: 'bootstrap',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/device/bootstrap',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    saveRawContext: {
      description: 'saveRawContext',
      isAuthenticated: true,
      verb: 'PUT',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/heroes/context/raw',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
    finalizePreview: {
      description: 'finalizePreview',
      isAuthenticated: true,
      verb: 'POST',
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: '/api/context/finalize-preview',
      mustStringify: true,
      isFlatResponse: false,
      isPicsUrl: false,
      contentType: 'application/json',
    },
  },
};

export default AppConfig;
