import { ImageSourcePropType } from 'react-native';

// Static mapping of classic images that Metro can resolve at build time
const CLASSIC_IMAGES: Record<string, any> = {
  'a.jpg': require('../assets/classic/a.jpg'),
  'after.jpg': require('../assets/classic/after.jpg'),
  'afternoon.jpg': require('../assets/classic/afternoon.jpg'),
  'all.jpg': require('../assets/classic/all.jpg'),
  'always.jpg': require('../assets/classic/always.jpg'),
  'answer.jpg': require('../assets/classic/answer.jpg'),
  'apple.jpg': require('../assets/classic/apple.jpg'),
  'april.jpg': require('../assets/classic/april.jpg'),
  'arm.jpg': require('../assets/classic/arm.jpg'),
  'ask.jpg': require('../assets/classic/ask.jpg'),
  'august.jpg': require('../assets/classic/august.jpg'),
  'aunt.jpg': require('../assets/classic/aunt.jpg'),
  'b.jpg': require('../assets/classic/b.jpg'),
  'baby.jpg': require('../assets/classic/baby.jpg'),
  'back.jpg': require('../assets/classic/back.jpg'),
  'backyard.jpg': require('../assets/classic/backyard.jpg'),
  'bad.jpg': require('../assets/classic/bad.jpg'),
  'ball.jpg': require('../assets/classic/ball.jpg'),
  'banana.jpg': require('../assets/classic/banana.jpg'),
  'bathroom.jpg': require('../assets/classic/bathroom.jpg'),
  'be.jpg': require('../assets/classic/be.jpg'),
  'beach.jpg': require('../assets/classic/beach.jpg'),
  'beans.jpg': require('../assets/classic/beans.jpg'),
  'bed.jpg': require('../assets/classic/bed.jpg'),
  'bedroom.jpg': require('../assets/classic/bedroom.jpg'),
  'beef.jpg': require('../assets/classic/beef.jpg'),
  'before.jpg': require('../assets/classic/before.jpg'),
  'better.jpg': require('../assets/classic/better.jpg'),
  'bicycle.jpg': require('../assets/classic/bicycle.jpg'),
  'big.jpg': require('../assets/classic/big.jpg'),
  'bike.jpg': require('../assets/classic/bike.jpg'),
  'black.jpg': require('../assets/classic/black.jpg'),
  'blue.jpg': require('../assets/classic/blue.jpg'),
  'blueberry.jpg': require('../assets/classic/blueberry.jpg'),
  'boat.jpg': require('../assets/classic/boat.jpg'),
  'book.jpg': require('../assets/classic/book.jpg'),
  'bowl.jpg': require('../assets/classic/bowl.jpg'),
  'bread.jpg': require('../assets/classic/bread.jpg'),
  'bright.jpg': require('../assets/classic/bright.jpg'),
  'broccoli.jpg': require('../assets/classic/broccoli.jpg'),
  'broken.jpg': require('../assets/classic/broken.jpg'),
  'brother.jpg': require('../assets/classic/brother.jpg'),
  'brown.jpg': require('../assets/classic/brown.jpg'),
  'brush.jpg': require('../assets/classic/brush.jpg'),
  'build.jpg': require('../assets/classic/build.jpg'),
  'bus.jpg': require('../assets/classic/bus.jpg'),
  'butter.jpg': require('../assets/classic/butter.jpg'),
  'c.jpg': require('../assets/classic/c.jpg'),
  'cake.jpg': require('../assets/classic/cake.jpg'),
  'call.jpg': require('../assets/classic/call.jpg'),
  'calm.jpg': require('../assets/classic/calm.jpg'),
  'can.jpg': require('../assets/classic/can.jpg'),
  'car.jpg': require('../assets/classic/car.jpg'),
  'carrot.jpg': require('../assets/classic/carrot.jpg'),
  'carry.jpg': require('../assets/classic/carry.jpg'),
  'cereal.jpg': require('../assets/classic/cereal.jpg'),
  'chair.jpg': require('../assets/classic/chair.jpg'),
  'cheese.jpg': require('../assets/classic/cheese.jpg'),
  'chicken.jpg': require('../assets/classic/chicken.jpg'),
  'chips.jpg': require('../assets/classic/chips.jpg'),
  'chocolate.jpg': require('../assets/classic/chocolate.jpg'),
  'choose.jpg': require('../assets/classic/choose.jpg'),
  'circle.jpg': require('../assets/classic/circle.jpg'),
  'classroom.jpg': require('../assets/classic/classroom.jpg'),
  'clean.jpg': require('../assets/classic/clean.jpg'),
  'climb.jpg': require('../assets/classic/climb.jpg'),
  'close.jpg': require('../assets/classic/close.jpg'),
  'closed.jpg': require('../assets/classic/closed.jpg'),
  'clothing.jpg': require('../assets/classic/clothing.jpg'),
  'cold.jpg': require('../assets/classic/cold.jpg'),
  'colors.jpg': require('../assets/classic/colors.jpg'),
  'come.jpg': require('../assets/classic/come.jpg'),
  'computer.jpg': require('../assets/classic/computer.jpg'),
  'cook.jpg': require('../assets/classic/cook.jpg'),
  'cool.jpg': require('../assets/classic/cool.jpg'),
  'corn.jpg': require('../assets/classic/corn.jpg'),
  'count.jpg': require('../assets/classic/count.jpg'),
  'cousin.jpg': require('../assets/classic/cousin.jpg'),
  'cream.jpg': require('../assets/classic/cream.jpg'),
  'create.jpg': require('../assets/classic/create.jpg'),
  'cucumber.jpg': require('../assets/classic/cucumber.jpg'),
  'cup.jpg': require('../assets/classic/cup.jpg'),
  'cut.jpg': require('../assets/classic/cut.jpg'),
  'd.jpg': require('../assets/classic/d.jpg'),
  'dad.jpg': require('../assets/classic/dad.jpg'),
  'dance.jpg': require('../assets/classic/dance.jpg'),
  'dark.jpg': require('../assets/classic/dark.jpg'),
  'day.jpg': require('../assets/classic/day.jpg'),
  'december.jpg': require('../assets/classic/december.jpg'),
  'decide.jpg': require('../assets/classic/decide.jpg'),
  'dentist.jpg': require('../assets/classic/dentist.jpg'),
  'description.jpg': require('../assets/classic/description.jpg'),
  'diamond.jpg': require('../assets/classic/diamond.jpg'),
  'different.jpg': require('../assets/classic/different.jpg'),
  'dirty.jpg': require('../assets/classic/dirty.jpg'),
  'do.jpg': require('../assets/classic/do.jpg'),
  'doctor.jpg': require('../assets/classic/doctor.jpg'),
  'down.jpg': require('../assets/classic/down.jpg'),
  'draw.jpg': require('../assets/classic/draw.jpg'),
  'dress.jpg': require('../assets/classic/dress.jpg'),
  'drink.jpg': require('../assets/classic/drink.jpg'),
  'dry.jpg': require('../assets/classic/dry.jpg'),
  'e.jpg': require('../assets/classic/e.jpg'),
  'ear.jpg': require('../assets/classic/ear.jpg'),
  'early.jpg': require('../assets/classic/early.jpg'),
  'eat.jpg': require('../assets/classic/eat.jpg'),
  'egg.jpg': require('../assets/classic/egg.jpg'),
  'eggs.jpg': require('../assets/classic/eggs.jpg'),
  'empty.jpg': require('../assets/classic/empty.jpg'),
  'enough.jpg': require('../assets/classic/enough.jpg'),
  'evening.jpg': require('../assets/classic/evening.jpg'),
  'excited.jpg': require('../assets/classic/excited.jpg'),
  'explain.jpg': require('../assets/classic/explain.jpg'),
  'extra.jpg': require('../assets/classic/extra.jpg'),
  'eye.jpg': require('../assets/classic/eye.jpg'),
  'f.jpg': require('../assets/classic/f.jpg'),
  'fall.jpg': require('../assets/classic/fall.jpg'),
  'fast.jpg': require('../assets/classic/fast.jpg'),
  'february.jpg': require('../assets/classic/february.jpg'),
  'feel.jpg': require('../assets/classic/feel.jpg'),
  'feelings.jpg': require('../assets/classic/feelings.jpg'),
  'finish.jpg': require('../assets/classic/finish.jpg'),
  'first.jpg': require('../assets/classic/first.jpg'),
  'fish.jpg': require('../assets/classic/fish.jpg'),
  'fix.jpg': require('../assets/classic/fix.jpg'),
  'food.jpg': require('../assets/classic/food.jpg'),
  'foot.jpg': require('../assets/classic/foot.jpg'),
  'fork.jpg': require('../assets/classic/fork.jpg'),
  'fresh.jpg': require('../assets/classic/fresh.jpg'),
  'friday.jpg': require('../assets/classic/friday.jpg'),
  'friend.jpg': require('../assets/classic/friend.jpg'),
  'fruits.jpg': require('../assets/classic/fruits.jpg'),
  'full.jpg': require('../assets/classic/full.jpg'),
  'g.jpg': require('../assets/classic/g.jpg'),
  'get.jpg': require('../assets/classic/get.jpg'),
  'give.jpg': require('../assets/classic/give.jpg'),
  'go.jpg': require('../assets/classic/go.jpg'),
  'good.jpg': require('../assets/classic/good.jpg'),
  'grapes.jpg': require('../assets/classic/grapes.jpg'),
  'gray.jpg': require('../assets/classic/gray.jpg'),
  'green.jpg': require('../assets/classic/green.jpg'),
  'grocery_store.jpg': require('../assets/classic/grocery_store.jpg'),
  'h.jpg': require('../assets/classic/h.jpg'),
  'hand.jpg': require('../assets/classic/hand.jpg'),
  'hard.jpg': require('../assets/classic/hard.jpg'),
  'hat.jpg': require('../assets/classic/hat.jpg'),
  'hate.jpg': require('../assets/classic/hate.jpg'),
  'have.jpg': require('../assets/classic/have.jpg'),
  'head.jpg': require('../assets/classic/head.jpg'),
  'hear.jpg': require('../assets/classic/hear.jpg'),
  'heart.jpg': require('../assets/classic/heart.jpg'),
  'help.jpg': require('../assets/classic/help.jpg'),
  'here.jpg': require('../assets/classic/here.jpg'),
  'home.jpg': require('../assets/classic/home.jpg'),
  'hospital.jpg': require('../assets/classic/hospital.jpg'),
  'hot.jpg': require('../assets/classic/hot.jpg'),
  'hour.jpg': require('../assets/classic/hour.jpg'),
  'how.jpg': require('../assets/classic/how.jpg'),
  'huge.jpg': require('../assets/classic/huge.jpg'),
  'hurt.jpg': require('../assets/classic/hurt.jpg'),
  'i.jpg': require('../assets/classic/i.jpg'),
  'ice_cream.jpg': require('../assets/classic/ice_cream.jpg'),
  'in.jpg': require('../assets/classic/in.jpg'),
  'invite.jpg': require('../assets/classic/invite.jpg'),
  'j.jpg': require('../assets/classic/j.jpg'),
  'jacket.jpg': require('../assets/classic/jacket.jpg'),
  'january.jpg': require('../assets/classic/january.jpg'),
  'join.jpg': require('../assets/classic/join.jpg'),
  'juice.jpg': require('../assets/classic/juice.jpg'),
  'july.jpg': require('../assets/classic/july.jpg'),
  'jump.jpg': require('../assets/classic/jump.jpg'),
  'june.jpg': require('../assets/classic/june.jpg'),
  'k.jpg': require('../assets/classic/k.jpg'),
  'kitchen.jpg': require('../assets/classic/kitchen.jpg'),
  'knife.jpg': require('../assets/classic/knife.jpg'),
  'know.jpg': require('../assets/classic/know.jpg'),
  'l.jpg': require('../assets/classic/l.jpg'),
  'lamp.jpg': require('../assets/classic/lamp.jpg'),
  'laptop.jpg': require('../assets/classic/laptop.jpg'),
  'last.jpg': require('../assets/classic/last.jpg'),
  'late.jpg': require('../assets/classic/late.jpg'),
  'later.jpg': require('../assets/classic/later.jpg'),
  'learn.jpg': require('../assets/classic/learn.jpg'),
  'leg.jpg': require('../assets/classic/leg.jpg'),
  'less.jpg': require('../assets/classic/less.jpg'),
  'lettuce.jpg': require('../assets/classic/lettuce.jpg'),
  'library.jpg': require('../assets/classic/library.jpg'),
  'light.jpg': require('../assets/classic/light.jpg'),
  'like.jpg': require('../assets/classic/like.jpg'),
  'listen.jpg': require('../assets/classic/listen.jpg'),
  'long.jpg': require('../assets/classic/long.jpg'),
  'look.jpg': require('../assets/classic/look.jpg'),
  'loud.jpg': require('../assets/classic/loud.jpg'),
  'love.jpg': require('../assets/classic/love.jpg'),
  'm.jpg': require('../assets/classic/m.jpg'),
  'make.jpg': require('../assets/classic/make.jpg'),
  'march.jpg': require('../assets/classic/march.jpg'),
  'may.jpg': require('../assets/classic/may.jpg'),
  'milk.jpg': require('../assets/classic/milk.jpg'),
  'mine.jpg': require('../assets/classic/mine.jpg'),
  'minute.jpg': require('../assets/classic/minute.jpg'),
  'monday.jpg': require('../assets/classic/monday.jpg'),
  'month.jpg': require('../assets/classic/month.jpg'),
  'more.jpg': require('../assets/classic/more.jpg'),
  'morning.jpg': require('../assets/classic/morning.jpg'),
  'motorcycle.jpg': require('../assets/classic/motorcycle.jpg'),
  'mouth.jpg': require('../assets/classic/mouth.jpg'),
  'move.jpg': require('../assets/classic/move.jpg'),
  'n.jpg': require('../assets/classic/n.jpg'),
  'narrow.jpg': require('../assets/classic/narrow.jpg'),
  'need.jpg': require('../assets/classic/need.jpg'),
  'never.jpg': require('../assets/classic/never.jpg'),
  'new.jpg': require('../assets/classic/new.jpg'),
  'next.jpg': require('../assets/classic/next.jpg'),
  'night.jpg': require('../assets/classic/night.jpg'),
  'no.jpg': require('../assets/classic/no.jpg'),
  'noisy.jpg': require('../assets/classic/noisy.jpg'),
  'nose.jpg': require('../assets/classic/nose.jpg'),
  'not.jpg': require('../assets/classic/not.jpg'),
  'november.jpg': require('../assets/classic/november.jpg'),
  'now.jpg': require('../assets/classic/now.jpg'),
  'nurse.jpg': require('../assets/classic/nurse.jpg'),
  'o.jpg': require('../assets/classic/o.jpg'),
  'oatmeal.jpg': require('../assets/classic/oatmeal.jpg'),
  'october.jpg': require('../assets/classic/october.jpg'),
  'often.jpg': require('../assets/classic/often.jpg'),
  'old.jpg': require('../assets/classic/old.jpg'),
  'on.jpg': require('../assets/classic/on.jpg'),
  'open.jpg': require('../assets/classic/open.jpg'),
  'orange.jpg': require('../assets/classic/orange.jpg'),
  'out.jpg': require('../assets/classic/out.jpg'),
  'oval.jpg': require('../assets/classic/oval.jpg'),
  'p.jpg': require('../assets/classic/p.jpg'),
  'paint.jpg': require('../assets/classic/paint.jpg'),
  'pants.jpg': require('../assets/classic/pants.jpg'),
  'paper.jpg': require('../assets/classic/paper.jpg'),
  'park.jpg': require('../assets/classic/park.jpg'),
  'pasta.jpg': require('../assets/classic/pasta.jpg'),
  'peas.jpg': require('../assets/classic/peas.jpg'),
  'pen.jpg': require('../assets/classic/pen.jpg'),
  'pencil.jpg': require('../assets/classic/pencil.jpg'),
  'people.jpg': require('../assets/classic/people.jpg'),
  'phone.jpg': require('../assets/classic/phone.jpg'),
  'pizza.jpg': require('../assets/classic/pizza.jpg'),
  'plan.jpg': require('../assets/classic/plan.jpg'),
  'plate.jpg': require('../assets/classic/plate.jpg'),
  'play.jpg': require('../assets/classic/play.jpg'),
  'playground.jpg': require('../assets/classic/playground.jpg'),
  'please.jpg': require('../assets/classic/please.jpg'),
  'pool.jpg': require('../assets/classic/pool.jpg'),
  'popcorn.jpg': require('../assets/classic/popcorn.jpg'),
  'practice.jpg': require('../assets/classic/practice.jpg'),
  'pretend.jpg': require('../assets/classic/pretend.jpg'),
  'pull.jpg': require('../assets/classic/pull.jpg'),
  'purple.jpg': require('../assets/classic/purple.jpg'),
  'push.jpg': require('../assets/classic/push.jpg'),
  'put.jpg': require('../assets/classic/put.jpg'),
  'q.jpg': require('../assets/classic/q.jpg'),
  'quantity.jpg': require('../assets/classic/quantity.jpg'),
  'question.jpg': require('../assets/classic/question.jpg'),
  'quiet.jpg': require('../assets/classic/quiet.jpg'),
  'r.jpg': require('../assets/classic/r.jpg'),
  'race.jpg': require('../assets/classic/race.jpg'),
  'read.jpg': require('../assets/classic/read.jpg'),
  'record.jpg': require('../assets/classic/record.jpg'),
  'rectangle.jpg': require('../assets/classic/rectangle.jpg'),
  'red.jpg': require('../assets/classic/red.jpg'),
  'remember.jpg': require('../assets/classic/remember.jpg'),
  'repeat.jpg': require('../assets/classic/repeat.jpg'),
  'rest.jpg': require('../assets/classic/rest.jpg'),
  'restaurant.jpg': require('../assets/classic/restaurant.jpg'),
  'rice.jpg': require('../assets/classic/rice.jpg'),
  'right.jpg': require('../assets/classic/right.jpg'),
  'run.jpg': require('../assets/classic/run.jpg'),
  's.jpg': require('../assets/classic/s.jpg'),
  'safe.jpg': require('../assets/classic/safe.jpg'),
  'salad.jpg': require('../assets/classic/salad.jpg'),
  'same.jpg': require('../assets/classic/same.jpg'),
  'sandwich.jpg': require('../assets/classic/sandwich.jpg'),
  'saturday.jpg': require('../assets/classic/saturday.jpg'),
  'say.jpg': require('../assets/classic/say.jpg'),
  'school.jpg': require('../assets/classic/school.jpg'),
  'second.jpg': require('../assets/classic/second.jpg'),
  'see.jpg': require('../assets/classic/see.jpg'),
  'september.jpg': require('../assets/classic/september.jpg'),
  'shape.jpg': require('../assets/classic/shape.jpg'),
  'share.jpg': require('../assets/classic/share.jpg'),
  'shirt.jpg': require('../assets/classic/shirt.jpg'),
  'short.jpg': require('../assets/classic/short.jpg'),
  'show.jpg': require('../assets/classic/show.jpg'),
  'sick.jpg': require('../assets/classic/sick.jpg'),
  'sing.jpg': require('../assets/classic/sing.jpg'),
  'sister.jpg': require('../assets/classic/sister.jpg'),
  'sit.jpg': require('../assets/classic/sit.jpg'),
  'sleep.jpg': require('../assets/classic/sleep.jpg'),
  'slow.jpg': require('../assets/classic/slow.jpg'),
  'small.jpg': require('../assets/classic/small.jpg'),
  'smell.jpg': require('../assets/classic/smell.jpg'),
  'snack.jpg': require('../assets/classic/snack.jpg'),
  'snacks.jpg': require('../assets/classic/snacks.jpg'),
  'soap.jpg': require('../assets/classic/soap.jpg'),
  'soft.jpg': require('../assets/classic/soft.jpg'),
  'sometimes.jpg': require('../assets/classic/sometimes.jpg'),
  'soon.jpg': require('../assets/classic/soon.jpg'),
  'sound.jpg': require('../assets/classic/sound.jpg'),
  'soup.jpg': require('../assets/classic/soup.jpg'),
  'speed.jpg': require('../assets/classic/speed.jpg'),
  'spoon.jpg': require('../assets/classic/spoon.jpg'),
  'spring.jpg': require('../assets/classic/spring.jpg'),
  'square.jpg': require('../assets/classic/square.jpg'),
  'stand.jpg': require('../assets/classic/stand.jpg'),
  'star.jpg': require('../assets/classic/star.jpg'),
  'start.jpg': require('../assets/classic/start.jpg'),
  'stomach.jpg': require('../assets/classic/stomach.jpg'),
  'stop.jpg': require('../assets/classic/stop.jpg'),
  'strawberry.jpg': require('../assets/classic/strawberry.jpg'),
  'summer.jpg': require('../assets/classic/summer.jpg'),
  'sunday.jpg': require('../assets/classic/sunday.jpg'),
  'sweet.jpg': require('../assets/classic/sweet.jpg'),
  't.jpg': require('../assets/classic/t.jpg'),
  'table.jpg': require('../assets/classic/table.jpg'),
  'tablet.jpg': require('../assets/classic/tablet.jpg'),
  'take.jpg': require('../assets/classic/take.jpg'),
  'talk.jpg': require('../assets/classic/talk.jpg'),
  'tall.jpg': require('../assets/classic/tall.jpg'),
  'taste.jpg': require('../assets/classic/taste.jpg'),
  'taxi.jpg': require('../assets/classic/taxi.jpg'),
  'tea.jpg': require('../assets/classic/tea.jpg'),
  'teacher.jpg': require('../assets/classic/teacher.jpg'),
  'tell.jpg': require('../assets/classic/tell.jpg'),
  'temperature.jpg': require('../assets/classic/temperature.jpg'),
  'the.jpg': require('../assets/classic/the.jpg'),
  'then.jpg': require('../assets/classic/then.jpg'),
  'there.jpg': require('../assets/classic/there.jpg'),
  'thick.jpg': require('../assets/classic/thick.jpg'),
  'thin.jpg': require('../assets/classic/thin.jpg'),
  'think.jpg': require('../assets/classic/think.jpg'),
  'throw.jpg': require('../assets/classic/throw.jpg'),
  'thursday.jpg': require('../assets/classic/thursday.jpg'),
  'time.jpg': require('../assets/classic/time.jpg'),
  'tired.jpg': require('../assets/classic/tired.jpg'),
  'toast.jpg': require('../assets/classic/toast.jpg'),
  'today.jpg': require('../assets/classic/today.jpg'),
  'tomato.jpg': require('../assets/classic/tomato.jpg'),
  'tomorrow.jpg': require('../assets/classic/tomorrow.jpg'),
  'tonight.jpg': require('../assets/classic/tonight.jpg'),
  'towel.jpg': require('../assets/classic/towel.jpg'),
  'toy.jpg': require('../assets/classic/toy.jpg'),
  'train.jpg': require('../assets/classic/train.jpg'),
  'triangle.jpg': require('../assets/classic/triangle.jpg'),
  'try.jpg': require('../assets/classic/try.jpg'),
  'tuesday.jpg': require('../assets/classic/tuesday.jpg'),
  'turn.jpg': require('../assets/classic/turn.jpg'),
  'tv.jpg': require('../assets/classic/tv.jpg'),
  'type.jpg': require('../assets/classic/type.jpg'),
  'u.jpg': require('../assets/classic/u.jpg'),
  'uncle.jpg': require('../assets/classic/uncle.jpg'),
  'up.jpg': require('../assets/classic/up.jpg'),
  'usually.jpg': require('../assets/classic/usually.jpg'),
  'v.jpg': require('../assets/classic/v.jpg'),
  'van.jpg': require('../assets/classic/van.jpg'),
  'vegetables.jpg': require('../assets/classic/vegetables.jpg'),
  'w.jpg': require('../assets/classic/w.jpg'),
  'wait.jpg': require('../assets/classic/wait.jpg'),
  'walk.jpg': require('../assets/classic/walk.jpg'),
  'want.jpg': require('../assets/classic/want.jpg'),
  'warm.jpg': require('../assets/classic/warm.jpg'),
  'wash.jpg': require('../assets/classic/wash.jpg'),
  'watch.jpg': require('../assets/classic/watch.jpg'),
  'water.jpg': require('../assets/classic/water.jpg'),
  'watermelon.jpg': require('../assets/classic/watermelon.jpg'),
  'wednesday.jpg': require('../assets/classic/wednesday.jpg'),
  'week.jpg': require('../assets/classic/week.jpg'),
  'weekend.jpg': require('../assets/classic/weekend.jpg'),
  'wet.jpg': require('../assets/classic/wet.jpg'),
  'when.jpg': require('../assets/classic/when.jpg'),
  'where.jpg': require('../assets/classic/where.jpg'),
  'white.jpg': require('../assets/classic/white.jpg'),
  'why.jpg': require('../assets/classic/why.jpg'),
  'wide.jpg': require('../assets/classic/wide.jpg'),
  'winter.jpg': require('../assets/classic/winter.jpg'),
  'working.jpg': require('../assets/classic/working.jpg'),
  'worse.jpg': require('../assets/classic/worse.jpg'),
  'write.jpg': require('../assets/classic/write.jpg'),
  'wrong.jpg': require('../assets/classic/wrong.jpg'),
  'x.jpg': require('../assets/classic/x.jpg'),
  'y.jpg': require('../assets/classic/y.jpg'),
  'year.jpg': require('../assets/classic/year.jpg'),
  'yellow.jpg': require('../assets/classic/yellow.jpg'),
  'yes.jpg': require('../assets/classic/yes.jpg'),
  'yesterday.jpg': require('../assets/classic/yesterday.jpg'),
  'yogurt.jpg': require('../assets/classic/yogurt.jpg'),
  'z.jpg': require('../assets/classic/z.jpg'),
  // Folder images
  'verbs.jpg': require('../assets/classic/verbs.jpg'),
  'things.jpg': require('../assets/classic/things.jpg'),
  'places.jpg': require('../assets/classic/places.jpg'),
  'pronouns.jpg': require('../assets/classic/pronouns.jpg'),
  'questions.jpg': require('../assets/classic/questions.jpg'),
  'shortcuts.jpg': require('../assets/classic/shortcuts.jpg'),
  'more_words.jpg': require('../assets/classic/more_words.jpg'),
  'more_people.jpg': require('../assets/classic/more_people.jpg'),
  'time_and_routine.jpg': require('../assets/classic/time_and_routine.jpg'),
  'times_of_day.jpg': require('../assets/classic/times_of_day.jpg'),
  'cuisine.jpg': require('../assets/classic/cuisine.jpg'),
  'dairy.jpg': require('../assets/classic/dairy.jpg'),
  'drinks.jpg': require('../assets/classic/drinks.jpg'),
  'duration.jpg': require('../assets/classic/duration.jpg'),
  'electronics.jpg': require('../assets/classic/electronics.jpg'),
  'frequency.jpg': require('../assets/classic/frequency.jpg'),
  'letters.jpg': require('../assets/classic/letters.jpg'),
  'meals.jpg': require('../assets/classic/meals.jpg'),
  'months.jpg': require('../assets/classic/months.jpg'),
  'numbers.jpg': require('../assets/classic/numbers.jpg'),
  'profession.jpg': require('../assets/classic/profession.jpg'),
  'proteins.jpg': require('../assets/classic/proteins.jpg'),
  'seasons.jpg': require('../assets/classic/seasons.jpg'),
  'texture.jpg': require('../assets/classic/texture.jpg'),
  'transportation.jpg': require('../assets/classic/transportation.jpg'),
  'this_week.jpg': require('../assets/classic/this_week.jpg'),
  'next_week.jpg': require('../assets/classic/next_week.jpg'),
  'last_week.jpg': require('../assets/classic/last_week.jpg'),
  'days_of_week.jpg': require('../assets/classic/days_of_week.jpg'),
  'ipad.jpg': require('../assets/classic/ipad.jpg'),
  'sight_words.jpg': require('../assets/classic/sight_words.jpg'),
  'body_parts.jpg': require('../assets/classic/body_parts.jpg'),
  // Pronoun images
  'you.jpg': require('../assets/classic/you.jpg'),
  'my.jpg': require('../assets/classic/my.jpg'),
  'me.jpg': require('../assets/classic/me.jpg'),
  'it.jpg': require('../assets/classic/it.jpg'),
  'that.jpg': require('../assets/classic/that.jpg'),
  'this.jpg': require('../assets/classic/this.jpg'),
  'your.jpg': require('../assets/classic/your.jpg'),
  'they.jpg': require('../assets/classic/they.jpg'),
  'them.jpg': require('../assets/classic/them.jpg'),
  'what.jpg': require('../assets/classic/what.jpg'),
  'who.jpg': require('../assets/classic/who.jpg'),
  'he.jpg': require('../assets/classic/he.jpg'),
  'she.jpg': require('../assets/classic/she.jpg'),
  'him.jpg': require('../assets/classic/him.jpg'),
  'her.jpg': require('../assets/classic/her.jpg'),
  'we.jpg': require('../assets/classic/we.jpg'),
  'us.jpg': require('../assets/classic/us.jpg'),
  'their.jpg': require('../assets/classic/their.jpg'),
  'our.jpg': require('../assets/classic/our.jpg'),
  'these.jpg': require('../assets/classic/these.jpg'),
  'those.jpg': require('../assets/classic/those.jpg'),
  'myself.jpg': require('../assets/classic/myself.jpg'),
  'yourself.jpg': require('../assets/classic/yourself.jpg'),
  'themselves.jpg': require('../assets/classic/themselves.jpg'),
  'himself.jpg': require('../assets/classic/himself.jpg'),
  'herself.jpg': require('../assets/classic/herself.jpg'),
  'ourselves.jpg': require('../assets/classic/ourselves.jpg'),
  // Verb subfolder images
  'sense_and_think.jpg': require('../assets/classic/sense_and_think.jpg'),
  'talk_and_ask.jpg': require('../assets/classic/talk_and_ask.jpg'),
  'food_and_drink_actions.jpg': require('../assets/classic/food_and_drink_actions.jpg'),
  'body_and_self-care.jpg': require('../assets/classic/body_and_self-care.jpg'),
  'home_and_chores.jpg': require('../assets/classic/home_and_chores.jpg'),
  'school_and_work.jpg': require('../assets/classic/school_and_work.jpg'),
  'play_and_create.jpg': require('../assets/classic/play_and_create.jpg'),
  'feel_and_be.jpg': require('../assets/classic/feel_and_be.jpg'),
  'device_and_media.jpg': require('../assets/classic/device_and_media.jpg'),
  'social_and_help.jpg': require('../assets/classic/social_and_help.jpg'),
  // Question images
  'is.jpg': require('../assets/classic/is.jpg'),
  'are.jpg': require('../assets/classic/are.jpg'),
  'am.jpg': require('../assets/classic/am.jpg'),
  'does.jpg': require('../assets/classic/does.jpg'),
  'did.jpg': require('../assets/classic/did.jpg'),
  'could.jpg': require('../assets/classic/could.jpg'),
  'will.jpg': require('../assets/classic/will.jpg'),
  'would.jpg': require('../assets/classic/would.jpg'),
  'should.jpg': require('../assets/classic/should.jpg'),
  'which.jpg': require('../assets/classic/which.jpg'),
  'how_many.jpg': require('../assets/classic/how_many.jpg'),
  'how_much.jpg': require('../assets/classic/how_much.jpg'),
  'how_long.jpg': require('../assets/classic/how_long.jpg'),
  'how_far.jpg': require('../assets/classic/how_far.jpg'),
  'questionmark.png': require('../assets/classic/questionmark.jpg'), // Note: file is .jpg but seed data uses .png
  'where_is.jpg': require('../assets/classic/where_is.jpg'),
  'what_is.jpg': require('../assets/classic/what_is.jpg'),
  'can_i.jpg': require('../assets/classic/can_i.jpg'),
  'can_you.jpg': require('../assets/classic/can_you.jpg'),
  'can_we.jpg': require('../assets/classic/can_we.jpg'),
  // People images
  'mom.jpg': require('../assets/classic/mom.jpg'),
  'best_friend.jpg': require('../assets/classic/best_friend.jpg'),
  'classmate.jpg': require('../assets/classic/classmate.jpg'),
  'grandma.jpg': require('../assets/classic/grandma.jpg'),
  'grandpa.jpg': require('../assets/classic/grandpa.jpg'),
  'school_nurse.jpg': require('../assets/classic/school_nurse.jpg'),
  'slp.jpg': require('../assets/classic/slp.jpg'),
  'ot.jpg': require('../assets/classic/ot.jpg'),
  'pt.jpg': require('../assets/classic/pt.jpg'),
  // Food action images
  'bite.jpg': require('../assets/classic/bite.jpg'),
  'chew.jpg': require('../assets/classic/chew.jpg'),
  'sip.jpg': require('../assets/classic/sip.jpg'),
  'swallow.jpg': require('../assets/classic/swallow.jpg'),
  // Food subfolder images
  'grains_and_carbs.jpg': require('../assets/classic/grains_and_carbs.jpg'),
  'sweets_desserts.jpg': require('../assets/classic/sweets_desserts.jpg'),
  'sauces_and_condiments.jpg': require('../assets/classic/sauces_and_condiments.jpg'),
  // Things images
  'shoes.jpg': require('../assets/classic/shoes.jpg'),
  'backpack.jpg': require('../assets/classic/backpack.jpg'),
  'notebook.jpg': require('../assets/classic/notebook.jpg'),
  'charger.jpg': require('../assets/classic/charger.jpg'),
  'remote.jpg': require('../assets/classic/remote.jpg'),
  'toys_and_games.jpg': require('../assets/classic/toys_and_games.jpg'),
  'school_supplies.jpg': require('../assets/classic/school_supplies.jpg'),
  'home_and_furniture.jpg': require('../assets/classic/home_and_furniture.jpg'),
  'outdoors_and_sports.jpg': require('../assets/classic/outdoors_and_sports.jpg'),
  'art_and_crafts.jpg': require('../assets/classic/art_and_crafts.jpg'),
  'medicine_and_care.jpg': require('../assets/classic/medicine_and_care.jpg'),
  // School supplies images
  'eraser.jpg': require('../assets/classic/eraser.jpg'),
  'marker.jpg': require('../assets/classic/marker.jpg'),
  'scissors.jpg': require('../assets/classic/scissors.jpg'),
  'glue.jpg': require('../assets/classic/glue.jpg'),
  'ruler.jpg': require('../assets/classic/ruler.jpg'),
  'folder.jpg': require('../assets/classic/folder.jpg'),
  'calculator.jpg': require('../assets/classic/calculator.jpg'),
  // Places images
  'living_room.jpg': require('../assets/classic/living_room.jpg'),
  'cafeteria.jpg': require('../assets/classic/cafeteria.jpg'),
  'playroom.jpg': require('../assets/classic/playroom.jpg'),
  'therapy.jpg': require('../assets/classic/therapy.jpg'),
  // Clothing images
  'socks.jpg': require('../assets/classic/socks.jpg'),
  'gloves.jpg': require('../assets/classic/gloves.jpg'),
  'shorts.jpg': require('../assets/classic/shorts.jpg'),
  // Additional missing images from seed data
  '1.jpg': require('../assets/classic/1.jpg'),
  '10.jpg': require('../assets/classic/10.jpg'),
  '100.jpg': require('../assets/classic/100.jpg'),
  '1000.jpg': require('../assets/classic/1000.jpg'),
  '11.jpg': require('../assets/classic/11.jpg'),
  '12.jpg': require('../assets/classic/12.jpg'),
  '2.jpg': require('../assets/classic/2.jpg'),
  '3.jpg': require('../assets/classic/3.jpg'),
  '4.jpg': require('../assets/classic/4.jpg'),
  '5.jpg': require('../assets/classic/5.jpg'),
  '6.jpg': require('../assets/classic/6.jpg'),
  '7.jpg': require('../assets/classic/7.jpg'),
  '8.jpg': require('../assets/classic/8.jpg'),
  '9.jpg': require('../assets/classic/9.jpg'),
  'a_little.jpg': require('../assets/classic/a_little.jpg'),
  'a_lot.jpg': require('../assets/classic/a_lot.jpg'),
  'airplane.jpg': require('../assets/classic/airplane.jpg'),
  'allowed.jpg': require('../assets/classic/allowed.jpg'),
  'ambulance.jpg': require('../assets/classic/ambulance.jpg'),
  'american.jpg': require('../assets/classic/american.jpg'),
  'and.jpg': require('../assets/classic/and.jpg'),
  'at.jpg': require('../assets/classic/at.jpg'),
  'bad_smell.jpg': require('../assets/classic/bad_smell.jpg'),
  'bitter.jpg': require('../assets/classic/bitter.jpg'),
  'bland.jpg': require('../assets/classic/bland.jpg'),
  'blanket.jpg': require('../assets/classic/blanket.jpg'),
  'blocks.jpg': require('../assets/classic/blocks.jpg'),
  'brightness_and_light.jpg': require('../assets/classic/brightness_and_light.jpg'),
  'bumpy.jpg': require('../assets/classic/bumpy.jpg'),
  'burger.jpg': require('../assets/classic/burger.jpg'),
  'cards.jpg': require('../assets/classic/cards.jpg'),
  'charge.jpg': require('../assets/classic/charge.jpg'),
  'chewy.jpg': require('../assets/classic/chewy.jpg'),
  'chinese.jpg': require('../assets/classic/chinese.jpg'),
  'clay.jpg': require('../assets/classic/clay.jpg'),
  'color.jpg': require('../assets/classic/color.jpg'),
  'comb.jpg': require('../assets/classic/comb.jpg'),
  'condition_and_state.jpg': require('../assets/classic/condition_and_state.jpg'),
  'controller.jpg': require('../assets/classic/controller.jpg'),
  'cookie.jpg': require('../assets/classic/cookie.jpg'),
  'cottage_cheese.jpg': require('../assets/classic/cottage_cheese.jpg'),
  'couch.jpg': require('../assets/classic/couch.jpg'),
  'crackers.jpg': require('../assets/classic/crackers.jpg'),
  'crayons.jpg': require('../assets/classic/crayons.jpg'),
  'crunchy.jpg': require('../assets/classic/crunchy.jpg'),
  'dawn.jpg': require('../assets/classic/dawn.jpg'),
  'delivery_truck.jpg': require('../assets/classic/delivery_truck.jpg'),
  'dim.jpg': require('../assets/classic/dim.jpg'),
  'dislike.jpg': require('../assets/classic/dislike.jpg'),
  'doll.jpg': require('../assets/classic/doll.jpg'),
  'donut.jpg': require('../assets/classic/donut.jpg'),
  'dull.jpg': require('../assets/classic/dull.jpg'),
  'fire_truck.jpg': require('../assets/classic/fire_truck.jpg'),
  'fixed.jpg': require('../assets/classic/fixed.jpg'),
  'for.jpg': require('../assets/classic/for.jpg'),
  'freezing.jpg': require('../assets/classic/freezing.jpg'),
  'frisbee.jpg': require('../assets/classic/frisbee.jpg'),
  'from.jpg': require('../assets/classic/from.jpg'),
  'garbage_truck.jpg': require('../assets/classic/garbage_truck.jpg'),
  'good_smell.jpg': require('../assets/classic/good_smell.jpg'),
  'granola_bar.jpg': require('../assets/classic/granola_bar.jpg'),
  'headphones.jpg': require('../assets/classic/headphones.jpg'),
  'helicopter.jpg': require('../assets/classic/helicopter.jpg'),
  'helmet.jpg': require('../assets/classic/helmet.jpg'),
  'hot_chocolate.jpg': require('../assets/classic/hot_chocolate.jpg'),
  'hurry.jpg': require('../assets/classic/hurry.jpg'),
  'italian.jpg': require('../assets/classic/italian.jpg'),
  'japanese.jpg': require('../assets/classic/japanese.jpg'),
  'jump_rope.jpg': require('../assets/classic/jump_rope.jpg'),
  'kayak.jpg': require('../assets/classic/kayak.jpg'),
  'ketchup.jpg': require('../assets/classic/ketchup.jpg'),
  'markers.jpg': require('../assets/classic/markers.jpg'),
  'mayo.jpg': require('../assets/classic/mayo.jpg'),
  'mexican.jpg': require('../assets/classic/mexican.jpg'),
  'mop.jpg': require('../assets/classic/mop.jpg'),
  'muffin.jpg': require('../assets/classic/muffin.jpg'),
  'mustard.jpg': require('../assets/classic/mustard.jpg'),
  'napkin.jpg': require('../assets/classic/napkin.jpg'),
  'none.jpg': require('../assets/classic/none.jpg'),
  'noodles.jpg': require('../assets/classic/noodles.jpg'),
  'noon.jpg': require('../assets/classic/noon.jpg'),
  'not_allowed.jpg': require('../assets/classic/not_allowed.jpg'),
  'not_working.jpg': require('../assets/classic/not_working.jpg'),
  'nuggets.jpg': require('../assets/classic/nuggets.jpg'),
  'nuts.jpg': require('../assets/classic/nuts.jpg'),
  'okay.jpg': require('../assets/classic/okay.jpg'),
  'pancake.jpg': require('../assets/classic/pancake.jpg'),
  'pause.jpg': require('../assets/classic/pause.jpg'),
  'peanut_butter.jpg': require('../assets/classic/peanut_butter.jpg'),
  'pickup_truck.jpg': require('../assets/classic/pickup_truck.jpg'),
  'pillow.jpg': require('../assets/classic/pillow.jpg'),
  'pink.jpg': require('../assets/classic/pink.jpg'),
  'police_car.jpg': require('../assets/classic/police_car.jpg'),
  'pretzel.jpg': require('../assets/classic/pretzel.jpg'),
  'puzzle.jpg': require('../assets/classic/puzzle.jpg'),
  'ranch.jpg': require('../assets/classic/ranch.jpg'),
  'rarely.jpg': require('../assets/classic/rarely.jpg'),
  'rough.jpg': require('../assets/classic/rough.jpg'),
  'salty.jpg': require('../assets/classic/salty.jpg'),
  'school_bus.jpg': require('../assets/classic/school_bus.jpg'),
  'scooter.jpg': require('../assets/classic/scooter.jpg'),
  'shampoo.jpg': require('../assets/classic/shampoo.jpg'),
  'shiny.jpg': require('../assets/classic/shiny.jpg'),
  'silent.jpg': require('../assets/classic/silent.jpg'),
  'size_and_length.jpg': require('../assets/classic/size_and_length.jpg'),
  'skateboard.jpg': require('../assets/classic/skateboard.jpg'),
  'slimy.jpg': require('../assets/classic/slimy.jpg'),
  'slow_down.jpg': require('../assets/classic/slow_down.jpg'),
  'smooth.jpg': require('../assets/classic/smooth.jpg'),
  'smoothie.jpg': require('../assets/classic/smoothie.jpg'),
  'soda.jpg': require('../assets/classic/soda.jpg'),
  'some.jpg': require('../assets/classic/some.jpg'),
  'sour.jpg': require('../assets/classic/sour.jpg'),
  'soy_sauce.jpg': require('../assets/classic/soy_sauce.jpg'),
  'spicy.jpg': require('../assets/classic/spicy.jpg'),
  'sponge.jpg': require('../assets/classic/sponge.jpg'),
  'steady.jpg': require('../assets/classic/steady.jpg'),
  'steak.jpg': require('../assets/classic/steak.jpg'),
  'stickers.jpg': require('../assets/classic/stickers.jpg'),
  'sticky.jpg': require('../assets/classic/sticky.jpg'),
  'stinky.jpg': require('../assets/classic/stinky.jpg'),
  'straw.jpg': require('../assets/classic/straw.jpg'),
  'stretchy.jpg': require('../assets/classic/stretchy.jpg'),
  'stroller.jpg': require('../assets/classic/stroller.jpg'),
  'stuffed_animal.jpg': require('../assets/classic/stuffed_animal.jpg'),
  'subway.jpg': require('../assets/classic/subway.jpg'),
  'sweep.jpg': require('../assets/classic/sweep.jpg'),
  'syrup.jpg': require('../assets/classic/syrup.jpg'),
  'take_turns.jpg': require('../assets/classic/take_turns.jpg'),
  'tape.jpg': require('../assets/classic/tape.jpg'),
  'throw_away.jpg': require('../assets/classic/throw_away.jpg'),
  'tiny.jpg': require('../assets/classic/tiny.jpg'),
  'to.jpg': require('../assets/classic/to.jpg'),
  'tofu.jpg': require('../assets/classic/tofu.jpg'),
  'toilet_paper.jpg': require('../assets/classic/toilet_paper.jpg'),
  'toothbrush.jpg': require('../assets/classic/toothbrush.jpg'),
  'toothpaste.jpg': require('../assets/classic/toothpaste.jpg'),
  'tortilla.jpg': require('../assets/classic/tortilla.jpg'),
  'tow_truck.jpg': require('../assets/classic/tow_truck.jpg'),
  'tractor.jpg': require('../assets/classic/tractor.jpg'),
  'undress.jpg': require('../assets/classic/undress.jpg'),
  'unsafe.jpg': require('../assets/classic/unsafe.jpg'),
  'vegan.jpg': require('../assets/classic/vegan.jpg'),
  'vegetarian.jpg': require('../assets/classic/vegetarian.jpg'),
  'veggies.jpg': require('../assets/classic/veggies.jpg'),
  'video_game.jpg': require('../assets/classic/video_game.jpg'),
  'waffle.jpg': require('../assets/classic/waffle.jpg'),
  'was.jpg': require('../assets/classic/was.jpg'),
  'wheelchair.jpg': require('../assets/classic/wheelchair.jpg'),
  'wipe.jpg': require('../assets/classic/wipe.jpg'),
  'with.jpg': require('../assets/classic/with.jpg'),
  'questionmark.jpg': require('../assets/classic/questionmark.jpg'),
  // ShortCuts images
  'shortCuts/attention/hi.jpg': require('../assets/shortCuts/attention/hi.jpg'),
  'shortCuts/attention/listen.jpg': require('../assets/shortCuts/attention/listen.jpg'),
  'shortCuts/attention/look.jpg': require('../assets/shortCuts/attention/look.jpg'),
  'shortCuts/attention/myturn.jpg': require('../assets/shortCuts/attention/myturn.jpg'),
  'shortCuts/attention/question.jpg': require('../assets/shortCuts/attention/question.jpg'),
  'shortCuts/attention/stop.jpg': require('../assets/shortCuts/attention/stop.jpg'),
  'shortCuts/actions/close.png': require('../assets/shortCuts/actions/close.png'),
  'shortCuts/actions/give.png': require('../assets/shortCuts/actions/give.png'),
  'shortCuts/actions/open.png': require('../assets/shortCuts/actions/open.png'),
  'shortCuts/actions/take.png': require('../assets/shortCuts/actions/take.png'),
  'shortCuts/actions/turnOff.png': require('../assets/shortCuts/actions/turnOff.png'),
  'shortCuts/actions/turnOn.png': require('../assets/shortCuts/actions/turnOn.png'),
  'shortCuts/fun/book.jpg': require('../assets/shortCuts/fun/book.jpg'),
  'shortCuts/fun/game.jpg': require('../assets/shortCuts/fun/game.jpg'),
  'shortCuts/fun/go.png': require('../assets/shortCuts/fun/go.png'),
  'shortCuts/fun/mine.jpg': require('../assets/shortCuts/fun/mine.jpg'),
  'shortCuts/fun/outside.jpg': require('../assets/shortCuts/fun/outside.jpg'),
  'shortCuts/fun/play.jpg': require('../assets/shortCuts/fun/play.jpg'),
  'shortCuts/positions/down.jpg': require('../assets/shortCuts/positions/down.jpg'),
  'shortCuts/positions/in.jpg': require('../assets/shortCuts/positions/in.jpg'),
  'shortCuts/positions/on.jpg': require('../assets/shortCuts/positions/on.jpg'),
  'shortCuts/positions/out.jpg': require('../assets/shortCuts/positions/out.jpg'),
  'shortCuts/positions/under.jpg': require('../assets/shortCuts/positions/under.jpg'),
  'shortCuts/positions/up.jpg': require('../assets/shortCuts/positions/up.jpg'),
  'shortCuts/wantNeed/alldone.jpg': require('../assets/shortCuts/wantNeed/alldone.jpg'),
  'shortCuts/wantNeed/bathroom.jpg': require('../assets/shortCuts/wantNeed/bathroom.jpg'),
  'shortCuts/wantNeed/drink.jpg': require('../assets/shortCuts/wantNeed/drink.jpg'),
  'shortCuts/wantNeed/eat.jpg': require('../assets/shortCuts/wantNeed/eat.jpg'),
  'shortCuts/wantNeed/help.jpg': require('../assets/shortCuts/wantNeed/help.jpg'),
  'shortCuts/wantNeed/more.jpg': require('../assets/shortCuts/wantNeed/more.jpg'),
  'shortCuts/wantNeed/sleep.jpg': require('../assets/shortCuts/wantNeed/sleep.jpg'),
  // Feelings images
  'feelings/goodFeelings/happy.jpg': require('../assets/feelings/goodFeelings/happy.jpg'),
  'feelings/badFeeling/sad.jpg': require('../assets/feelings/badFeeling/sad.jpg'),
  'feelings/badFeeling/angry.jpg': require('../assets/feelings/badFeeling/angry.jpg'),
  'feelings/goodFeelings/excited.jpg': require('../assets/feelings/goodFeelings/excited.jpg'),
  'feelings/goodFeelings/calm.jpg': require('../assets/feelings/goodFeelings/calm.jpg'),
  'feelings/badFeeling/worried.jpg': require('../assets/feelings/badFeeling/worried.jpg'),
  'feelings/badFeeling/scared.jpg': require('../assets/feelings/badFeeling/scared.jpg'),
  'feelings/goodFeelings/proud.jpg': require('../assets/feelings/goodFeelings/proud.jpg'),
  'feelings/goodFeelings/loved.jpg': require('../assets/feelings/goodFeelings/loved.jpg'),
  'feelings/goodFeelings/silly.jpg': require('../assets/feelings/goodFeelings/silly.jpg'),
  'feelings/badFeeling/bored.jpg': require('../assets/feelings/badFeeling/bored.jpg'),
  'feelings/badFeeling/embarrassed.jpg': require('../assets/feelings/badFeeling/embarrassed.jpg'),
  'feelings/badBody/tired.jpg': require('../assets/feelings/badBody/tired.jpg'),
  'feelings/badBody/sick.jpg': require('../assets/feelings/badBody/sick.jpg'),
  'feelings/badBody/hurt.jpg': require('../assets/feelings/badBody/hurt.jpg'),
  'feelings/badBody/cold.jpg': require('../assets/feelings/badBody/cold.jpg'),
  'feelings/badBody/itchy.jpg': require('../assets/feelings/badBody/itchy.jpg'),
  'feelings/badBody/dizzy.jpg': require('../assets/feelings/badBody/dizzy.jpg'),
  'feelings/goodBody/comfortable.jpg': require('../assets/feelings/goodBody/comfortable.jpg'),
  'feelings/goodBody/energetic.jpg': require('../assets/feelings/goodBody/energetic.jpg'),
  'feelings/goodBody/ok.jpg': require('../assets/feelings/goodBody/ok.jpg'),
  'feelings/goodBody/relaxed.jpg': require('../assets/feelings/goodBody/relaxed.jpg'),
  'feelings/goodBody/strong.jpg': require('../assets/feelings/goodBody/strong.jpg'),
  'feelings/goodBody/warm.jpg': require('../assets/feelings/goodBody/warm.jpg'),
};

/**
 * The standard placeholder image used for AI-created tiles that have no photo
 */
export const AI_PLACEHOLDER_IMAGE_URI = 'src/assets/taptoAdd.png';

/**
 * Resolves image source for sentence builder components
 * Handles different path formats and converts them to proper require statements
 */
export const resolveImageSource = (
  imageUri?: string,
): ImageSourcePropType | null => {
  if (!imageUri) {
    return null;
  }

  // Handle local placeholder image
  if (imageUri === AI_PLACEHOLDER_IMAGE_URI) {
    return require('../assets/taptoAdd.png');
  }

  // Handle HTTP URLs
  if (imageUri.startsWith('http')) {
    return { uri: imageUri };
  }

  // Handle file:// paths
  if (imageUri.startsWith('file://')) {
    return { uri: imageUri };
  }

  // Handle asset paths - use static mapping for classic images
  if (imageUri.startsWith('../assets/classic/')) {
    const fileName = imageUri.replace('../assets/classic/', '');
    return CLASSIC_IMAGES[fileName] || null;
  }

  if (imageUri.startsWith('../assets/classic/')) {
    const fileName = imageUri.replace('../assets/classic/', '');
    return CLASSIC_IMAGES[fileName] || null;
  }

  // Handle shortCuts asset paths
  if (imageUri.startsWith('../../assets/shortCuts/')) {
    const assetPath = imageUri.replace('../../assets/', '');
    return CLASSIC_IMAGES[assetPath] || null;
  }

  if (imageUri.startsWith('../assets/shortCuts/')) {
    const assetPath = imageUri.replace('../assets/', '');
    return CLASSIC_IMAGES[assetPath] || null;
  }

  // Handle feelings asset paths
  if (imageUri.startsWith('../../assets/feelings/')) {
    const assetPath = imageUri.replace('../../assets/', '');
    return CLASSIC_IMAGES[assetPath] || null;
  }

  if (imageUri.startsWith('../assets/feelings/')) {
    const assetPath = imageUri.replace('../assets/', '');
    return CLASSIC_IMAGES[assetPath] || null;
  }

  // Handle other asset paths
  if (imageUri.startsWith('../../assets/')) {
    const assetPath = imageUri.replace('../../assets/', '');
    return { uri: assetPath };
  }

  if (imageUri.startsWith('../assets/')) {
    const assetPath = imageUri.replace('../assets/', '');
    return { uri: assetPath };
  }

  // Fallback for other local paths
  return { uri: `file://${imageUri}` };
};

/**
 * Checks if an image URI is considered a placeholder
 */
export const isPlaceholderImage = (imageUri?: string): boolean => {
  if (!imageUri) {
    return true;
  }

  if (imageUri === AI_PLACEHOLDER_IMAGE_URI) {
    return true;
  }

  // If resolveImageSource returns null, it's either an invalid path or missing
  // which will result in the local welcome.png placeholder being shown
  if (resolveImageSource(imageUri) === null) {
    return true;
  }

  return false;
};
